<?xml version="1.0" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  <xacro:property name="camera_length" value="0.01" />
  <xacro:property name="camera_width" value="0.1" />
  <xacro:property name="camera_height" value="0.05" />

  <!-- Depth Camera Link -->
  <link name="depth_camera_link">
    <visual>
      <geometry>
        <box size="0.01 0.1 0.01"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.01 0.1 0.01"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="0.1" l="${camera_length}" w="${camera_width}" h="${camera_height}" 
                           xyz="0 0 0" rpy="0 0 0" />
  </link>

  <link name="depth_camera_link_optical">
  </link>

  <!-- Depth Camera Joint -->
  <joint name="base_depth_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="depth_camera_link"/>
    <origin rpy="0 0 0" xyz="${0.3 +(camera_length /2.0)} 0 0.2"/>
  </joint>
  
  <joint name="depth_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="depth_camera_link" />
        <child link="depth_camera_link_optical" />
  </joint>

  <!-- Depth Camera Sensor -->
    <gazebo reference="depth_camera_link">
        <material>Gazebo/Red</material>
        <sensor name="depth_camera_sensor" type="depth" >
            <pose>0 0 0 0 0 0 </pose>
            <image>
             <width>640</width>
             <height>480</height>
             <format>R8G8B8</format>
            </image>
            <clip>
                <near>0.005</near>
                <far>20.0</far>
            </clip>
            <visualize>true</visualize>
            <update_rate>20.0</update_rate>
            <plugin name="depth_camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>depth_camera_link_optical</frame_name>
       
            </plugin>
        </sensor>

    </gazebo>

</robot>
